services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: WscSquashApp
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DB_USER
        value: wscsquashapp_db_user
      - key: DB_PASSWORD
        value: QepsybtOpjfC3Pxbl8soELcgXgpZe47q
      - key: DB_DATABASE
        value: wscsquashapp_db
      - key: DB_HOST
        value: dpg-ci307h67avj2t36b3lr0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432

databases:
  - name: wscsquashapp
    databaseName: wscsquashapp_db

# postgres://wscsquashapp_db_user:QepsybtOpjfC3Pxbl8soELcgXgpZe47q@dpg-ci307h67avj2t36b3lr0-a/wscsquashapp_db
# postgres://wscsquashapp_db_user:QepsybtOpjfC3Pxbl8soELcgXgpZe47q@dpg-ci307h67avj2t36b3lr0-a.oregon-postgres.render.com/wscsquashapp_db
# PGPASSWORD=QepsybtOpjfC3Pxbl8soELcgXgpZe47q psql -h dpg-ci307h67avj2t36b3lr0-a.oregon-postgres.render.com -U wscsquashapp_db_user wscsquashapp_db
# postgres://wscsquashapp_db_user:QepsybtOpjfC3Pxbl8soELcgXgpZe47q@dpg-ci307h67avj2t36b3lr0-a/wscsquashapp_db