services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: WscSquashApp
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: admin
      - key: DB_DATABASE
        value: wscsquashapp
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432

databases:
  - name: wscsquashapp
    databaseName: wscsquashapp_db
    plan: free
